default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics/Internal Testing"
  lane :android_beta do
    # Build the AAB
    gradle(task: "bundle", build_type: "Release")

    # Upload to Google Play Internal Test Track
    upload_to_play_store(
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy a new version to the Google Play Store (Production)"
  lane :android_production do
    # Build the AAB
    gradle(task: "bundle", build_type: "Release")

    # Upload to Google Play Production Track
    upload_to_play_store(
      track: 'production',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false
    )
  end
end
