import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../core/api_client.dart';

class PatientReportTab extends StatefulWidget {
  final String patientId;

  const PatientReportTab({super.key, required this.patientId});

  @override
  State<PatientReportTab> createState() => _PatientReportTabState();
}

class _PatientReportTabState extends State<PatientReportTab> {
  bool _generating = false;
  String? _error;
  String? _reportMarkdown;
  
  // Dummy text for UI testing until the backend LLM is fully wired
  final String _dummyReport = """
# Comprehensive AI Clinical Synthesis
*Generated on \${DateTime.now().toString().split(' ')[0]}*

---

## 1. Bio-Psycho-Social Formulation
The patient presents with an elevated physiological stress response, strongly correlating with recent **GAD-7 (18/21)** and **PSS-10 (29/40)** scores. Somatic complaints mapped via the Reflexology interface indicate high meridian tension in the upper cervical and thoracic regions, often associated with perceived hyper-responsibility.

## 2. Longitudinal Assessment Analysis
- **PHQ-9:** Dropped from 14 to 9 over the last 3 phases, indicating a moderate response to behavioral activation.
- **Trauma (PCL-5):** Hovering at 35, safely below the provisional diagnosis threshold, but intrusive clusters remain active.
- **Art Therapy (FEATS):** The latest PPAT submission showed significantly improved *Color Fit* and *Space Integration*, suggesting improved ego strength.

## 3. Diagnostic Impressions
* Unspecified Somatic Symptom Disorder
* Generalized Anxiety Disorder (Improving)

## 4. Care Plan Recommendations
1. **Transition from Phase 1 to Phase 2:** The patient demonstrates sufficient stabilization. Ready for targeted EMDR or deeper core processing.
2. **Assign Metahealth Scanning:** Recommend assigning the Metahealth Body Scanner homework to better isolate somatic triggers.

---
*Note: This synthesis is generated by the AI Diagnostic Engine and should be reviewed by a licensed clinician before inclusion in the official medical record.*
  """;

  Future<void> _generateReport() async {
    setState(() {
      _generating = true;
      _error = null;
    });

    try {
      final resp = await ApiClient.instance.post(
        '/patients/\${widget.patientId}/report/generate',
        body: jsonEncode({
           "include_homework": true,
           "include_assessments": true,
           "include_sessions": true
        }),
      );
      
      if (resp.statusCode == 200) {
        // Here we would normally poll for completion or use the raw markdown.
        // For now, we simulate the LLM delay and display the structured markdown.
        await Future.delayed(const Duration(seconds: 2));
        setState(() => _reportMarkdown = _dummyReport);
      } else {
        setState(() => _error = "Engine failed to initialize synthesis. HTTP \${resp.statusCode}");
      }
    } catch (e) {
      setState(() => _error = "Network failure.");
    } finally {
      if (mounted) setState(() => _generating = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_reportMarkdown != null) {
      return Container(
        color: Colors.white,
        child: Column(
          children: [
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
              decoration: BoxDecoration(
                border: Border(bottom: BorderSide(color: Colors.grey.shade200)),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('Professional Report', style: GoogleFonts.inter(fontWeight: FontWeight.bold, color: const Color(0xFF8FB9A8))),
                  Row(
                    children: [
                      TextButton.icon(
                        icon: const Icon(Icons.refresh, size: 16),
                        label: const Text('Regenerate'),
                        onPressed: _generateReport,
                        style: TextButton.styleFrom(iconColor: Colors.grey, foregroundColor: Colors.grey),
                      ),
                      const SizedBox(width: 8),
                      ElevatedButton.icon(
                        icon: const Icon(Icons.print, size: 16),
                        label: const Text('Export PDF'),
                        style: ElevatedButton.styleFrom(
                           backgroundColor: const Color(0xFF8FB9A8),
                           foregroundColor: Colors.white,
                           elevation: 0,
                        ),
                        onPressed: () {},
                      ),
                    ],
                  ),
                ],
              ),
            ),
            Expanded(
              child: Markdown(
                data: _reportMarkdown!,
                styleSheet: MarkdownStyleSheet(
                  h1: GoogleFonts.inter(fontSize: 22, fontWeight: FontWeight.w800, color: const Color(0xFF2D3748)),
                  h2: GoogleFonts.inter(fontSize: 18, fontWeight: FontWeight.bold, color: const Color(0xFF8FB9A8)),
                  p: GoogleFonts.inter(fontSize: 14, height: 1.6, color: Colors.grey.shade800),
                  listBullet: const TextStyle(color: Color(0xFF8FB9A8)),
                ),
              ),
            ),
          ],
        ),
      );
    }

    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
             Container(
               padding: const EdgeInsets.all(24),
               decoration: BoxDecoration(
                 color: const Color(0xFF8FB9A8).withValues(alpha: 0.1),
                 shape: BoxShape.circle,
               ),
               child: Icon(Icons.auto_awesome, size: 48, color: const Color(0xFF8FB9A8)),
             ),
             const SizedBox(height: 24),
             Text(
               'AI Clinical Synthesizer',
               style: GoogleFonts.inter(fontSize: 20, fontWeight: FontWeight.bold, color: const Color(0xFF2D3748)),
             ),
             const SizedBox(height: 12),
             Text(
               'Generate a comprehensive, professional diagnostic report leveraging all longitudinal assessments, session notes, and specific trauma/somatic indicators.',
               textAlign: TextAlign.center,
               style: GoogleFonts.inter(fontSize: 14, color: Colors.grey.shade600, height: 1.5),
             ),
             const SizedBox(height: 32),
             if (_generating)
                const CircularProgressIndicator(color: Color(0xFF8FB9A8))
             else
                SizedBox(
                  width: double.infinity,
                  height: 50,
                  child: ElevatedButton.icon(
                    onPressed: _generateReport,
                    icon: const Icon(Icons.science),
                    label: const Text('Generate Professional Report', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: const Color(0xFF8FB9A8),
                      foregroundColor: Colors.white,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                      elevation: 0,
                    ),
                  ),
                ),
             if (_error != null)
                Padding(
                  padding: const EdgeInsets.only(top: 16.0),
                  child: Text(_error!, style: const TextStyle(color: Colors.red)),
                )
          ],
        ),
      ),
    );
  }
}
