import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Bell, Sparkles, ArrowRight, PenLine, AudioLines, ChevronRight, Shield, ArrowUp, Home, MessageCircle, ListChecks, LineChart, Check, Frown, Annoyed, Meh, Smile, Laugh, } from 'lucide-react';
const TABS = [
    { tab: 'home', label: 'Home', icon: Home },
    { tab: 'chat', label: 'Aria', icon: MessageCircle },
    { tab: 'tasks', label: 'Tasks', icon: ListChecks },
    { tab: 'progress', label: 'Progress', icon: LineChart },
];
const MOODS = [
    { icon: Frown, label: 'Low' },
    { icon: Annoyed, label: 'Meh' },
    { icon: Meh, label: 'Okay' },
    { icon: Smile, label: 'Good' },
    { icon: Laugh, label: 'Great' },
];
function greeting() {
    const hr = new Date().getHours();
    return hr < 12 ? 'Good morning' : hr < 18 ? 'Good afternoon' : 'Good evening';
}
export default function PatientApp() {
    const [tab, setTab] = useState('home');
    const [mood, setMood] = useState(2);
    return (_jsx("div", { className: "min-h-screen flex justify-center items-start p-4 pt-6", style: { background: 'radial-gradient(circle at 30% 0%, #eceef3, #d9dce4)' }, children: _jsxs("div", { className: "w-full max-w-[412px] bg-organic-bg rounded-[38px] shadow-organic-lg overflow-hidden relative min-h-[812px] flex flex-col", children: [_jsxs("div", { className: "px-[22px] pt-[22px] pb-3.5 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2.5", children: [_jsx("div", { className: "w-[42px] h-[42px] rounded-full bg-organic-accent-300 grid place-items-center font-bold text-organic-accent-900", children: "MO" }), _jsxs("div", { className: "leading-tight", children: [_jsx("div", { className: "text-xs text-organic-neutral-600", children: greeting() }), _jsx("div", { className: "font-heading text-lg", children: "Maya" })] })] }), _jsxs("button", { className: "w-10 h-10 rounded-full border border-organic-neutral-300/60 bg-organic-surface grid place-items-center relative", children: [_jsx(Bell, { size: 18 }), _jsx("span", { className: "absolute top-2 right-2.5 w-2 h-2 rounded-full bg-organic-accent" })] })] }), _jsxs("div", { className: "flex-1 overflow-y-auto px-5 pb-[108px] pt-1.5", children: [tab === 'home' && _jsx(HomeTab, { onGoChat: () => setTab('chat'), onGoTasks: () => setTab('tasks'), mood: mood, setMood: setMood }), tab === 'chat' && _jsx(ChatTab, {}), tab === 'tasks' && _jsx(TasksTab, {}), tab === 'progress' && _jsx(ProgressTab, {})] }), _jsx("div", { className: "absolute bottom-0 left-0 right-0 border-t border-organic-neutral-300/50 px-[18px] pt-3 pb-[22px] flex justify-between", style: { background: 'rgba(247, 248, 250, 0.92)', backdropFilter: 'blur(10px)' }, children: TABS.map(({ tab: t, label, icon: Icon }) => (_jsxs("button", { onClick: () => setTab(t), className: `flex-1 flex flex-col items-center gap-1 ${t === tab ? 'text-organic-accent' : 'text-organic-neutral-500'}`, children: [_jsx(Icon, { size: 23 }), _jsx("span", { className: `text-[10.5px] ${t === tab ? 'font-bold' : 'font-medium'}`, children: label })] }, t))) })] }) }));
}
// ─── Home ───────────────────────────────────────────────────────────────────
const HOME_TASKS = [
    { icon: PenLine, title: 'CBT thought record', meta: 'Worksheet · 10 min' },
    { icon: AudioLines, title: 'Evening breathing', meta: 'Audio · 6 min' },
];
function HomeTab({ onGoChat, onGoTasks, mood, setMood }) {
    return (_jsxs("div", { className: "flex flex-col gap-4", children: [_jsx("div", { className: "bg-gradient-to-br from-organic-accent-600 to-organic-accent-800 rounded-organic-tile p-[22px] text-organic-accent-100 relative overflow-hidden", children: _jsxs("div", { className: "relative", children: [_jsx("div", { className: "text-xs opacity-85 mb-1", children: "Next session" }), _jsx("div", { className: "font-heading text-[22px] mb-0.5", children: "Thursday \u00B7 10:00 AM" }), _jsx("div", { className: "text-[13px] opacity-85 mb-4", children: "with Dr. Heba Moustafa \u00B7 video call" }), _jsx("button", { className: "rounded-organic-pill bg-organic-accent-100 text-organic-accent-800 font-heading text-[13.5px] px-[18px] py-2.5", children: "Join & prepare" })] }) }), _jsxs("div", { className: "bg-organic-surface rounded-organic-card p-5 shadow-organic-sm", children: [_jsx("div", { className: "font-heading text-[17px] mb-3.5", children: "How are you feeling today?" }), _jsx("div", { className: "flex justify-between gap-1.5", children: MOODS.map((m, i) => {
                            const sel = mood === i;
                            return (_jsxs("button", { onClick: () => setMood(i), className: `flex-1 rounded-organic-tile py-3 flex flex-col items-center gap-1.5 ${sel ? 'bg-organic-accent-200' : 'bg-organic-neutral-100'}`, children: [_jsx(m.icon, { size: 22, className: sel ? 'text-organic-accent-800' : 'text-organic-neutral-600' }), _jsx("span", { className: `text-[10.5px] font-semibold ${sel ? 'text-organic-accent-800' : 'text-organic-neutral-600'}`, children: m.label })] }, m.label));
                        }) })] }), _jsxs("div", { children: [_jsxs("div", { className: "flex justify-between items-center mb-2.5", children: [_jsx("h3", { className: "text-lg font-heading", children: "Today's tasks" }), _jsx("button", { onClick: onGoTasks, className: "text-[12.5px] text-organic-accent", children: "See all" })] }), _jsx("div", { className: "flex flex-col gap-2.5", children: HOME_TASKS.map((t) => (_jsxs("div", { className: "flex items-center gap-3.5 bg-organic-surface rounded-organic-tile p-3.5 shadow-organic-sm", children: [_jsx("div", { className: "w-10 h-10 rounded-organic-tile bg-organic-accent-100 grid place-items-center flex-none", children: _jsx(t.icon, { size: 19, className: "text-organic-accent-700" }) }), _jsxs("div", { className: "flex-1", children: [_jsx("div", { className: "font-semibold text-sm", children: t.title }), _jsx("div", { className: "text-xs text-organic-neutral-600", children: t.meta })] }), _jsx(ChevronRight, { size: 18, className: "text-organic-neutral-500" })] }, t.title))) })] }), _jsxs("button", { onClick: onGoChat, className: "bg-organic-accent-2-100 rounded-organic-tile p-[18px] flex items-center gap-3.5 text-left", children: [_jsx("div", { className: "w-[46px] h-[46px] rounded-full bg-organic-accent-2-500 grid place-items-center flex-none", children: _jsx(Sparkles, { size: 22, className: "text-organic-accent-2-100" }) }), _jsxs("div", { className: "flex-1", children: [_jsx("div", { className: "font-heading text-base text-organic-accent-2-900", children: "Talk to Aria" }), _jsx("div", { className: "text-[12.5px] text-organic-accent-2-800", children: "Your AI companion, here anytime" })] }), _jsx(ArrowRight, { size: 19, className: "text-organic-accent-2-700" })] })] }));
}
// ─── Chat (Aria) ────────────────────────────────────────────────────────────
const CHAT_MESSAGES = [
    { who: 'ai', text: "Hi Maya, I'm glad you're here. How has your week felt so far?" },
    { who: 'me', text: "A bit up and down. Work has been stressful and I haven't slept well." },
    { who: 'ai', text: "That sounds draining. When your sleep dips, what tends to be on your mind as you're lying awake?" },
    { who: 'me', text: "Mostly worrying I'll fall behind on everything." },
];
const CHIPS = ['I feel anxious', 'Help me reframe this', 'A grounding exercise'];
function ChatTab() {
    return (_jsxs("div", { className: "flex flex-col gap-3", children: [_jsxs("div", { className: "flex items-center gap-2.5 pb-2", children: [_jsx("div", { className: "w-[42px] h-[42px] rounded-full bg-organic-accent-2-500 grid place-items-center", children: _jsx(Sparkles, { size: 20, className: "text-organic-accent-2-100" }) }), _jsxs("div", { children: [_jsx("div", { className: "font-heading text-lg", children: "Aria" }), _jsx("div", { className: "text-[11.5px] text-organic-accent-2-700", children: "\u25CF Always here to listen" })] })] }), CHAT_MESSAGES.map((m, i) => (_jsx("div", { className: `flex ${m.who === 'me' ? 'justify-end' : 'justify-start'}`, children: _jsx("div", { className: `max-w-[78%] px-4 py-3 text-sm leading-relaxed ${m.who === 'me'
                        ? 'bg-organic-accent text-organic-accent-100 rounded-2xl rounded-br-md'
                        : 'bg-organic-surface text-organic-text rounded-2xl rounded-bl-md'}`, children: m.text }) }, i))), _jsx("div", { className: "flex gap-2 flex-wrap mt-0.5", children: CHIPS.map((c) => (_jsx("span", { className: "text-[12.5px] px-3.5 py-2 rounded-organic-pill bg-organic-surface border border-organic-neutral-300/60 text-organic-neutral-800", children: c }, c))) }), _jsxs("div", { className: "flex items-center gap-2 py-2 pl-[18px] pr-2 bg-organic-surface border border-organic-neutral-300/60 rounded-organic-pill mt-1.5", children: [_jsx("span", { className: "flex-1 text-sm text-organic-neutral-500", children: "Share what's on your mind\u2026" }), _jsx("button", { className: "w-[38px] h-[38px] rounded-full bg-organic-accent grid place-items-center", children: _jsx(ArrowUp, { size: 19, className: "text-organic-accent-100" }) })] }), _jsxs("div", { className: "flex items-center gap-2 justify-center text-[11px] text-organic-neutral-600 mt-0.5", children: [_jsx(Shield, { size: 13 }), " Aria isn't a crisis service. In an emergency, call your local line."] })] }));
}
// ─── Tasks ──────────────────────────────────────────────────────────────────
const TASKS = [
    { title: 'Gratitude journal', meta: 'Completed today', type: 'Journal', done: true },
    { title: 'CBT thought record', meta: 'Due today', type: 'Worksheet', done: false },
    { title: 'Evening breathing', meta: 'Due today', type: 'Audio', done: false },
    { title: 'Read: Understanding worry', meta: 'Due Fri', type: 'Reading', done: false },
    { title: 'Morning walk log', meta: 'Completed yesterday', type: 'Activity', done: true },
];
function TasksTab() {
    const completed = TASKS.filter((t) => t.done).length;
    return (_jsxs("div", { className: "flex flex-col gap-4", children: [_jsx("h2", { className: "text-[26px] font-heading", children: "Your homework" }), _jsxs("div", { className: "bg-organic-accent-2-100 rounded-organic-tile px-[18px] py-4 flex items-center gap-3.5", children: [_jsxs("div", { className: "font-heading text-3xl text-organic-accent-2-800", children: [completed, "/", TASKS.length] }), _jsxs("div", { className: "flex-1", children: [_jsx("div", { className: "font-semibold text-[13.5px] text-organic-accent-2-900", children: "Completed this week" }), _jsx("div", { className: "h-1.5 rounded-organic-pill bg-organic-accent-2-200 mt-1.5 overflow-hidden", children: _jsx("div", { className: "h-full bg-organic-accent-2-500", style: { width: `${(completed / TASKS.length) * 100}%` } }) })] })] }), _jsx("div", { className: "flex flex-col gap-2.5", children: TASKS.map((t) => (_jsxs("div", { className: "flex items-center gap-3.5 bg-organic-surface rounded-organic-tile p-3.5 shadow-organic-sm", children: [_jsx("span", { className: `w-[26px] h-[26px] rounded-full flex-none grid place-items-center border-2 ${t.done ? 'bg-organic-accent-2-500 border-organic-accent-2-500' : 'border-organic-neutral-400'}`, children: t.done && _jsx(Check, { size: 14, className: "text-organic-accent-2-100" }) }), _jsxs("div", { className: "flex-1", children: [_jsx("div", { className: `font-semibold text-sm ${t.done ? 'text-organic-neutral-500 line-through' : 'text-organic-text'}`, children: t.title }), _jsx("div", { className: "text-xs text-organic-neutral-600", children: t.meta })] }), _jsx("span", { className: "text-[10.5px] px-2.5 py-0.5 rounded-organic-pill bg-organic-neutral-200 text-organic-neutral-700", children: t.type })] }, t.title))) })] }));
}
// ─── Progress ───────────────────────────────────────────────────────────────
const SCORES = [
    { name: 'PHQ-9 (depression)', now: 14, band: 'Mod. severe', delta: '↓ from 18', pct: 52, color: 'bg-organic-accent-500' },
    { name: 'GAD-7 (anxiety)', now: 11, band: 'Moderate', delta: '↓ from 15', pct: 52, color: 'bg-organic-accent-2-500' },
];
function ProgressTab() {
    return (_jsxs("div", { className: "flex flex-col gap-4", children: [_jsx("h2", { className: "text-[26px] font-heading", children: "Your progress" }), _jsxs("div", { className: "flex gap-3", children: [_jsxs("div", { className: "flex-1 bg-organic-surface rounded-organic-tile p-4 shadow-organic-sm", children: [_jsx("div", { className: "font-heading text-[28px] text-organic-accent-700", children: "12" }), _jsx("div", { className: "text-xs text-organic-neutral-600", children: "Day streak" })] }), _jsxs("div", { className: "flex-1 bg-organic-surface rounded-organic-tile p-4 shadow-organic-sm", children: [_jsx("div", { className: "font-heading text-[28px] text-organic-accent-2-700", children: "8" }), _jsx("div", { className: "text-xs text-organic-neutral-600", children: "Sessions done" })] })] }), _jsxs("div", { className: "bg-organic-surface rounded-organic-card p-5 shadow-organic-sm", children: [_jsxs("div", { className: "flex justify-between items-center mb-3.5", children: [_jsx("h3", { className: "text-[17px] font-heading", children: "Mood this month" }), _jsx("span", { className: "text-[11px] text-organic-accent-2-700 font-semibold", children: "Trending up" })] }), _jsxs("svg", { viewBox: "0 0 320 130", className: "w-full h-[130px]", children: [_jsx("defs", { children: _jsxs("linearGradient", { id: "patientMood", x1: "0", y1: "0", x2: "0", y2: "1", children: [_jsx("stop", { offset: "0", stopColor: "#c9903d", stopOpacity: "0.3" }), _jsx("stop", { offset: "1", stopColor: "#c9903d", stopOpacity: "0" })] }) }), _jsx("path", { d: "M0,90 L53,96 L106,72 L160,80 L213,54 L266,58 L320,34 L320,130 L0,130 Z", fill: "url(#patientMood)" }), _jsx("path", { d: "M0,90 L53,96 L106,72 L160,80 L213,54 L266,58 L320,34", fill: "none", stroke: "#c9903d", strokeWidth: 3, strokeLinecap: "round", strokeLinejoin: "round" })] })] }), _jsxs("div", { className: "bg-organic-surface rounded-organic-card p-5 shadow-organic-sm", children: [_jsx("h3", { className: "text-[17px] font-heading mb-3.5", children: "Assessment scores" }), _jsx("div", { className: "flex flex-col gap-3.5", children: SCORES.map((s) => (_jsxs("div", { children: [_jsxs("div", { className: "flex justify-between text-[13px] mb-1.5", children: [_jsx("span", { className: "font-semibold", children: s.name }), _jsxs("span", { className: "text-organic-neutral-700", children: [s.now, " \u00B7 ", s.band, " ", _jsx("span", { className: "text-organic-accent-2-700", children: s.delta })] })] }), _jsx("div", { className: "h-2 rounded-organic-pill bg-organic-neutral-200 overflow-hidden", children: _jsx("div", { className: `h-full ${s.color}`, style: { width: `${s.pct}%` } }) })] }, s.name))) })] })] }));
}
